CREATE TABLE INFOSAUDE.CHECAGEM_ELETRONICA_LOG (
    CD_LOG NUMBER(10) NOT NULL,
    DT_REGISTRO DATE NOT NULL,
    IN_OPERACAO CHAR(1) NOT NULL
)
/
CREATE OR REPLACE PUBLIC SYNONYM CHECAGEM_ELETRONICA_LOG FOR INFOSAUDE.CHECAGEM_ELETRONICA_LOG
/
GRANT DELETE, INSERT, SELECT, UPDATE ON INFOSAUDE.CHECAGEM_ELETRONICA_LOG TO ROLE_INFOSAUDE
/
COMMENT ON TABLE INFOSAUDE.CHECAGEM_ELETRONICA_LOG IS 'Log de operacoes da checagem eletronica.'
/
COMMENT ON COLUMN INFOSAUDE.CHECAGEM_ELETRONICA_LOG.CD_LOG IS 'Codigo do log.'
/
COMMENT ON COLUMN INFOSAUDE.CHECAGEM_ELETRONICA_LOG.DT_REGISTRO IS 'Data do registro.'
/
COMMENT ON COLUMN INFOSAUDE.CHECAGEM_ELETRONICA_LOG.IN_OPERACAO IS 'Tipo da operacao.'
/
