CREATE SEQUENCE INFOSAUDE.CHECAGEM_ELETRONICA_LOG
START WITH 1
MAXVALUE 99999999999
MINVALUE 1
INCREMENT BY 1
NOCYCLE
NOCACHE
/
CREATE OR REPLACE PUBLIC SYNONYM CHECAGEM_ELETRONICA_LOG FOR INFOSAUDE.CHECAGEM_ELETRONICA_LOG
/
GRANT SELECT ON INFOSAUDE.CHECAGEM_ELETRONICA_LOG TO ROLE_INFOSAUDE
/
